apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-nginx
  template:
    metadata:
      labels:
        app: flask-nginx
    spec:
      containers:
      - name: flask-nginx
        image: golapavitra918/e2e-example:v2
        ports:
        - containerPort: 80
