apiVersion: v1
kind: Service
metadata:
  name: flask-nginx-service
  namespace: deply2
spec:
  selector:
    app: flask-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
